[package]
name = "conds"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
chia = "0.9.0"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
serde_with = { version = "3.8.3", features = ["hex"] }
sha2 = "0.10.8"
